### ISSUE TITLE
Issues with yarn install

### ISSUE THREAD

**Issue by justingbauer** [muffinista/before-dawn#14]
warning " > bootstrap@4.3.1" has incorrect peer dependency "popper.js@^1.14.7".
[4/4] Building fresh packages...
[1/7] ⠐ desktop-idle
[2/7] ⠐ detect-fullscreen
[6/7] ⠐ node-sass
[7/7] ⠈ electron-chromedriver
error /home/kitchen/Scripts/before-dawn/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/kitchen/Scripts/before-dawn/node_modules/electron
Output:
Downloading tmp-12801-0-electron-v4.0.5-linux-arm.zip
Error: GET https://github.com/electron/electron/releases/download/v4.0.5/electron-v4.0.5-linux-arm.zip returned 404
/home/kitchen/Scripts/before-dawn/node_modules/electron/install.js:49
  throw err
  ^

Error: Failed to find Electron v4.0.5 for linux-arm at https://github.com/electron/electron/releases/download/v4.0.5/electron-v4.0.5-linux-arm.zip
    at Request.<anonymous> (/home/kitchen/Scripts/before-dawn/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:189:13)
    at Request.onRequestResponse (/home/kitchen/Scripts/before-dawn/node_modules/nugget/node_modules/request/request.js:1068:10)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)

**Comment by muffinista** [comment]
@justingbauer can you let me know what platform you're trying to build on? I'm guessing it's an RPi or another ARM platform but I'd love to know the specifics, thanks!
