### ISSUE TITLE
Failed to launch on windows, Not allowed to load local resource

### ISSUE THREAD

**Issue by kuroismith** [muffinista/before-dawn#16]
Got this message:
```
Not allowed to load local resource: file://c/Users/...../AppData/Local/Programs/before-dawn/resources/app.asar/output/prefs.html?screenshot=file%3A%2F%2FC%3A%5CUsers%5CWUQINC~1%5CAppData%5CLocal%5CTemp%5C201924-4492-1dybcd2.l6uph.png
```

**Comment by jankohlbach** [comment]
have exactly the same problem, downloaded the .exe in the newest version and all I see is a white screen in the app
in developer tools I can see the same error as 

> 
> 
> Got this message:
> 
> ```
> Not allowed to load local resource: file://c/Users/...../AppData/Local/Programs/before-dawn/resources/app.asar/output/prefs.html?screenshot=file%3A%2F%2FC%3A%5CUsers%5CWUQINC~1%5CAppData%5CLocal%5CTemp%5C201924-4492-1dybcd2.l6uph.png
> ```

**Comment by muffinista** [comment]
OK, thanks, this is super useful information! I'm working on a fix.

**Comment by kuroismith** [comment]
Also it failled to build a release in windows platform.

Got: `Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values`

Add `"webpack-sources": "1.0.1",` to `devDependencies` of package.json will fix this issue.

**Comment by muffinista** [comment]
@kuroismith I wonder if you can dump the entire output here. `webpack-sources` is already in the lockfile so I'm not really sure how adding it would help (also I can build releases on Windows)

**Comment by kuroismith** [comment]
@muffinista 

```
PS C:\Users\xxx\win\before-dawn> yarn run release
yarn run v1.13.0
$ yarn dist
$ yarn compile && electron-builder --x64
$ cross-env NODE_ENV=production webpack --mode production --config webpack.config.js
clean-webpack-plugin: C:\Users\xxx\win\before-dawn\output has been removed.
(node:8536) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
C:\Users\xxx\win\before-dawn\node_modules\source-map\lib\source-map-generator.js:276
        throw new Error(
        ^
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (C:\Users\xxx\win\before-dawn\node_modules\source-map\lib\source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (C:\Users\xxx\win\before-dawn\node_modules\source-map\lib\source-map-generator.js:110:12)
    at C:\Users\xxx\win\before-dawn\node_modules\source-map\lib\source-map-generator.js:72:17    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\xxx\win\before-dawn\node_modules\source-map\lib\source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (C:\Users\xxx\win\before-dawn\node_modules\source-map\lib\source-map-generator.js:48:24)
    at SourceMapSource.node (C:\Users\xxx\win\before-dawn\node_modules\webpack-sources\lib\SourceMapSource.js:32:35)
    at SourceMapSource.proto.sourceAndMap (C:\Users\xxx\win\before-dawn\node_modules\webpack-sources\lib\SourceAndMapMixin.js:30:18)
    at getTaskForFile (C:\Users\xxx\win\before-dawn\node_modules\webpack\lib\SourceMapDevToolPlugin.js:37:30)
    at files.forEach (C:\Users\xxx\win\before-dawn\node_modules\webpack\lib\SourceMapDevToolPlugin.js:136:20)
    at Array.forEach (<anonymous>)
    at compilation.hooks.afterOptimizeChunkAssets.tap (C:\Users\xxx\win\before-dawn\node_modules\webpack\lib\SourceMapDevToolPlugin.js:130:12)
    at SyncHook.eval [as call] (eval at create (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (C:\Users\xxx\win\before-dawn\node_modules\webpack\lib\Compilation.js:1315:42)
    at _err1 (eval at create (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:16:1)
    at taskRunner.run (C:\Users\xxx\win\before-dawn\node_modules\terser-webpack-plugin\dist\index.js:319:9)
    at TaskRunner.run (C:\Users\xxx\win\before-dawn\node_modules\terser-webpack-plugin\dist\TaskRunner.js:44:7)
    at TerserPlugin.optimizeFn (C:\Users\xxx\win\before-dawn\node_modules\terser-webpack-plugin\dist\index.js:225:18)
    at _err0 (eval at create (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at C:\Users\xxx\win\before-dawn\node_modules\babili-webpack-plugin\lib\index.js:106:11
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (C:\Users\xxx\win\before-dawn\node_modules\webpack\lib\Compilation.js:1311:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (C:\Users\xxx\win\before-dawn\node_modules\webpack\lib\Compilation.js:1307:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\Users\xxx\win\before-dawn\node_modules\webpack\lib\Compilation.js:1244:27)
    at hooks.make.callAsync.err (C:\Users\xxx\win\before-dawn\node_modules\webpack\lib\Compiler.js:624:17)
    at _err0 (eval at create (C:\Users\xxx\win\before-dawn\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _addModuleChain (C:\Users\xxx\win\before-dawn\node_modules\webpack\lib\Compilation.js:1095:12)
    at processModuleDependencies.err (C:\Users\xxx\win\before-dawn\node_modules\webpack\lib\Compilation.js:1007:9)    at process._tickCallback (internal/process/next_tick.js:61:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by muffinista** [comment]
OK, this should be working better now, thanks for the bug report! I just put out a release that should fix it https://github.com/muffinista/before-dawn/releases/tag/v0.10.8

**Comment by kuroismith** [comment]
0.10.8 build fix the white screen issue. many thanks.
